export const UsersResponses = {
  CREATE_SUCCESS: {
    en: 'User created successfully',
    pt: 'Usuário criado com sucesso',
    es: 'Usuario creado con éxito',
    fr: 'Utilisateur créé avec succès',
  },
  UPDATE_SUCCESS: {
    en: 'User updated successfully',
    pt: 'Usuário atualizado com sucesso',
    es: 'Usuario actualizado con éxito',
    fr: 'Utilisateur mis à jour avec succès',
  },
  DELETE_SUCCESS: {
    en: 'User deleted successfully',
    pt: 'Usuário excluído com sucesso',
    es: 'Usuario eliminado con éxito',
    fr: 'Utilisateur supprimé avec succès',
  },
  NOT_FOUND: {
    en: 'User not found',
    pt: 'Usuário não encontrado',
    es: 'Usuario no encontrado',
    fr: 'Utilisateur non trouvé',
  },
  DUPLICATE_ENTRY: {
    en: 'Duplicate entry detected',
    pt: 'Entrada duplicada detectada',
    es: 'Entrada duplicada detectada',
    fr: 'Entrée en double détectée',
  },
  RETRIEVED: {
    en: 'Users retrieved successfully',
    pt: 'Usuários recuperados com sucesso',
    es: 'Usuarios recuperados con éxito',
    fr: 'Les utilisateurs ont été récupérés avec succès',
  },
  CREATOR_NOT_FOUND: {
    en: 'Creator not found',
    pt: 'Usuário criador não encontrado',
    es: 'No se encontró el usuario creador',
    fr: 'Utilisateur créateur non trouvé',
  },
  COMPANY_NOT_ASSOCIATED_WITH_USER: {
    en: 'The provided company is not associated with the current user',
    pt: 'A empresa fornecida não está associada ao usuário atual',
    es: 'La empresa proporcionada no está asociada con el usuario actual',
    fr: `L'entreprise fournie n'est pas associée à l'utilisateur actuel`,
  },
  DEPARTMENT_NOT_FOUND: {
    en: 'Department not found',
    pt: 'Departamento não encontrado',
    es: 'Departamento no encontrado',
    fr: `Département non trouvé`,
  },
  DEPARTMENT_NOT_BELONG_COMPANY: {
    en: 'The provided department does not belong to the specified company',
    pt: 'O departamento fornecido não pertence à empresa especificada',
    es: 'El departamento proporcionado no pertenece a la empresa especificada',
    fr: `Le service fourni n'appartient pas à l'entreprise spécifiée`,
  },
  PROVIDE_A_ROLE: {
    en: 'At least one role must be provided',
    pt: 'Pelo menos um cargo deve ser fornecido',
    es: 'Se debe proporcionar al menos un rol',
    fr: `Au moins un rôle doit être fourni`,
  },
  ROLE_NOT_FOUND: {
    en: 'Role not found',
    pt: 'Cargo não encontrado',
    es: 'Rol no encontrado',
    fr: `Rôle non trouvé`,
  },
  ROLE_NOT_ASSOCIATE_WITH_COMPANY: {
    en: 'The role is not associated with the specified company',
    pt: 'O cargo não está associado à empresa especificada',
    es: 'El rol no está asociado con la empresa especificada',
    fr: `Le rôle n'est pas associé à l'entreprise spécifiée`,
  },
  NO_SELECTED_COMPANY: {
    en: 'There is no company selected for the current user',
    pt: 'Não há uma empresa selecionada para o usuário atual',
    es: 'No hay ninguna empresa seleccionada para el usuario actual',
    fr: `Aucune entreprise n'est sélectionnée pour l'utilisateur actuel`,
  },
  NOT_BELONG_TO_SELECTED_COMPANY: {
    en: 'User not found or does not belong to the selected company',
    pt: 'Usuário não encontrado ou não pertence à empresa selecionada',
    es: 'Usuario no encontrado o no pertenece a la empresa seleccionada',
    fr: `Utilisateur non trouvé ou n'appartient pas à l'entreprise sélectionnée`,
  },
  NO_PERMISSION_DELETE: {
    en: 'You do not have permission to delete this user',
    pt: 'Você não tem permissão para excluir este usuário',
    es: 'No tiene permiso para eliminar este usuario',
    fr: `Vous n'avez pas l'autorisation de supprimer cet utilisateur`,
  },
  COMPANY_NOT_FOUND: {
    en: 'Company not found',
    pt: 'Empresa não encontrada',
    es: 'Empresa no encontrada',
    fr: `Entreprise non trouvée`,
  },
  COMPANY_SELECTED_UPDATED: {
    en: 'Selected company has been updated successfully',
    pt: 'A empresa selecionada foi atualizada com sucesso',
    es: 'La empresa seleccionada se ha actualizado correctamente',
    fr: `L'entreprise sélectionnée a été mise à jour avec succès`,
  },
  OLD_PASSWORD_INCORRECT: {
    en: 'Old password is incorrect',
    pt: 'A senha está incorreta',
    es: 'La contraseña anterior es incorrecta',
    fr: `L'ancien mot de passe est incorrect`,
  },
  NEW_PASSWORD_SAME_OLD: {
    en: 'The new password cannot be the same as the previous one.',
    pt: 'A nova senha deve ser diferente da anterior.',
    es: 'La nueva contraseña no puede ser la misma que la anterior.',
    fr: `Le nouveau mot de passe ne peut pas être le même que le précédent.`,
  },
  PROVIDE_OLD_AND_NEW_PASSWORD: {
    en: 'Provide the old and the new password.',
    pt: 'Forneça a antiga e a nova senha.',
    es: 'Proporcione contraseña antigua y nueva.',
    fr: `Fournir l'ancien ate nouveau mot de passe`,
  },
  PASSWORD_UPDATED_SUCCESS: {
    en: 'Password update successfully.',
    pt: 'Senha atualizada com sucesso.',
    es: 'Contraseña actualizada.',
    fr: `Mot de passe mis à jour avec succès`,
  },
};
